package com.customer.fivecanale.landing.cartscreen;

public enum CartUiAction {
  MANAGE_ADDRESS, CHANGE_ADDRESS, BILLING_ADDRESS, CONTINUE_SHOPPING, EMPTY_CART, CROSS_CLICK,
  CLEAR, PROMO_CODE, CHANGE_PAYMENT,
  LOGIN_RESULT, LOGIN, PAYMENT, ON_SUCCESS, SUB_TOTAL, ENABLE_BACK, DISABLE_BACK
}
